# -*- encoding: utf-8 -*-

=begin
#EmailGuard Public API

#Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

The version of the OpenAPI document: 1.2
Contact: dev@emailguard.co
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "emailguard_sdk/version"

Gem::Specification.new do |s|
  s.name        = "emailguard_sdk"
  s.version     = Emailguard::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["EmailGuard"]
  s.email       = ["dev@emailguard.co"]
  s.homepage    = "https://emailguard.co"
  s.summary     = "EmailGuard public API Ruby SDK"
  s.description = "EmailGuard public API Ruby SDK. See https://emailguard.co/docs/api-reference/guides/sdk-ruby for setup, authentication, and examples."
  s.license     = "MIT"
  s.required_ruby_version = ">= 3.0"
  s.metadata    = {
    "homepage_uri" => "https://emailguard.co",
    "source_code_uri" => "https://github.com/EmailGuard/emailguard-ruby",
    "documentation_uri" => "https://emailguard.co/docs/api-reference/guides/sdk-ruby",
    "changelog_uri" => "https://emailguard.co/changelog"
  }

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = Dir["lib/**/*", "README.md", "LICENSE", "examples/**/*"]
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
