# Code generated by scripts/clients/generate-language-facades.mjs; DO NOT EDIT.
require "uri"

module Emailguard
  class APIError < StandardError
    attr_reader :status, :code
    def initialize(message, status: 0, code: nil)
      super(message)
      @status = status
      @code = code
    end
  end

  class ResourceClient
    private
    def unwrap
      envelope = yield
      raise APIError.new("API returned an empty response", code: "INVALID_RESPONSE") if envelope.nil?
      raise APIError.new(envelope.message || "API returned an unsuccessful response", status: 200, code: envelope.code) unless envelope.code == "SUCCESS"
      return nil unless envelope.respond_to?(:data)
      raise APIError.new("API response did not include data", status: 200, code: "INVALID_RESPONSE") if envelope.data.nil?
      envelope.data
    rescue ApiError => error
      body = error.response_body.to_s
      begin
        payload = JSON.parse(body.empty? ? "{}" : body)
        invalid_response = false
      rescue JSON::ParserError
        payload = {}
        invalid_response = true
      end
      raise APIError.new(
        invalid_response ? "API returned an invalid response" : (payload["message"] || error.message),
        status: error.code || 0,
        code: invalid_response ? "INVALID_RESPONSE" : payload["code"]
      )
    rescue JSON::ParserError, TypeError => error
      raise APIError.new("API returned an invalid response", code: "INVALID_RESPONSE")
    end
  end

  class InvitesClient < ResourceClient
    def initialize(api_client)
      @api = InvitesApi.new(api_client)
    end

    def cancel_pending_invite(invite_id:)
      unwrap { @api.cancel_pending_invite(invite_id) }
    end

    def invite_team_member(input:)
      unwrap { @api.invite_team_member(input) }
    end

    def list_pending_team_invites()
      unwrap { @api.list_pending_team_invites() }
    end
  end

  class ChannelsClient < ResourceClient
    def initialize(api_client)
      @api = ChannelsApi.new(api_client)
    end

    def create_notification_channel(input:)
      unwrap { @api.create_notification_channel(input) }
    end

    def delete_notification_channel(channel_id:)
      unwrap { @api.delete_notification_channel(channel_id) }
    end

    def list_notification_channels()
      unwrap { @api.list_notification_channels() }
    end

    def test_notification_channel(channel_id:)
      unwrap { @api.test_notification_channel(channel_id) }
    end

    def update_notification_channel(channel_id:, input:)
      unwrap { @api.update_notification_channel(channel_id, input) }
    end
  end

  class RulesClient < ResourceClient
    def initialize(api_client)
      @api = RulesApi.new(api_client)
    end

    def create_notification_rule(input:)
      unwrap { @api.create_notification_rule(input) }
    end

    def delete_notification_rule(rule_id:)
      unwrap { @api.delete_notification_rule(rule_id) }
    end

    def list_notification_rules()
      unwrap { @api.list_notification_rules() }
    end

    def update_notification_rule(rule_id:, input:)
      unwrap { @api.update_notification_rule(rule_id, input) }
    end
  end

  class EmailClient < ResourceClient
    def initialize(api_client)
      @api = EmailApi.new(api_client)
    end

    def detect_email(email:)
      unwrap { @api.detect_email(email: email) }
    end
  end

  class BillingClient < ResourceClient
    def initialize(api_client)
      @api = BillingApi.new(api_client)
    end

    def get_billing_usage(range: nil, start: nil, _end: nil)
      unwrap { @api.get_billing_usage(range: range, start: start, _end: _end) }
    end
  end

  class TeamsClient < ResourceClient
    def initialize(api_client)
      @api = TeamsApi.new(api_client)
    end

    def get_team()
      unwrap { @api.get_team() }
    end

    def update_team(input:)
      unwrap { @api.update_team(input) }
    end
  end

  class EventsClient < ResourceClient
    def initialize(api_client)
      @api = EventsApi.new(api_client)
    end

    def list_notification_events()
      unwrap { @api.list_notification_events() }
    end
  end

  class MembersClient < ResourceClient
    def initialize(api_client)
      @api = MembersApi.new(api_client)
    end

    def list_team_members()
      unwrap { @api.list_team_members() }
    end

    def remove_team_member(user_id:)
      unwrap { @api.remove_team_member(user_id) }
    end

    def update_team_member(user_id:, input:)
      unwrap { @api.update_team_member(user_id, input) }
    end
  end

  class Client
    attr_reader :invites, :channels, :rules, :email, :billing, :teams, :events, :members
    def initialize(api_key:, base_url: nil)
      configuration = Configuration.default
      if base_url
        configuration.host = base_url
        configuration.scheme = URI(base_url).scheme
      end
      configuration.api_key["Authorization"] = api_key
      configuration.api_key_prefix["Authorization"] = "Bearer"
      api_client = ApiClient.new(configuration)
      @invites = InvitesClient.new(api_client)
      @channels = ChannelsClient.new(api_client)
      @rules = RulesClient.new(api_client)
      @email = EmailClient.new(api_client)
      @billing = BillingClient.new(api_client)
      @teams = TeamsClient.new(api_client)
      @events = EventsClient.new(api_client)
      @members = MembersClient.new(api_client)
    end
  end
end
