=begin
#EmailGuard Public API

#Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

The version of the OpenAPI document: 1.0
Contact: dev@emailguard.co
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Emailguard::BillingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BillingApi' do
  before do
    # run before each test
    @api_instance = Emailguard::BillingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BillingApi' do
    it 'should create an instance of BillingApi' do
      expect(@api_instance).to be_instance_of(Emailguard::BillingApi)
    end
  end

  # unit tests for api_v1_team_billing_usage_get
  # Get billing usage
  # Returns metered feature usage for the team&#39;s billing period. Defaults to the current period; use &#x60;range&#x3D;previous&#x60; or &#x60;range&#x3D;custom&#x60; with &#x60;start&#x60; and &#x60;end&#x60; to query other windows.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :range Period selector: current, previous, or custom
  # @option opts [String] :start Custom range start (RFC3339 or YYYY-MM-DD); required when range&#x3D;custom
  # @option opts [String] :_end Custom range end (RFC3339 or YYYY-MM-DD); required when range&#x3D;custom
  # @return [BillingUsageResponse]
  describe 'api_v1_team_billing_usage_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
