=begin
#EmailGuard Public API

#Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

The version of the OpenAPI document: 1.0
Contact: dev@emailguard.co
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Emailguard::ChannelsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ChannelsApi' do
  before do
    # run before each test
    @api_instance = Emailguard::ChannelsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ChannelsApi' do
    it 'should create an instance of ChannelsApi' do
      expect(@api_instance).to be_instance_of(Emailguard::ChannelsApi)
    end
  end

  # unit tests for api_v1_team_notifications_channels_channel_id_delete
  # Delete notification channel
  # Permanently deletes a channel and removes it from any rules that reference it.
  # @param channel_id UUID of the notification channel to delete
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'api_v1_team_notifications_channels_channel_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_team_notifications_channels_channel_id_put
  # Update notification channel
  # Updates a channel&#39;s display name or configuration. Send only fields you want to change.
  # @param channel_id UUID of the notification channel to update
  # @param update_notification_channel_input Updated channel name and/or configuration
  # @param [Hash] opts the optional parameters
  # @return [GetNotificationChannelResponse]
  describe 'api_v1_team_notifications_channels_channel_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_team_notifications_channels_channel_id_test_post
  # Test notification channel
  # Sends a sample payload to a webhook channel to confirm the endpoint is reachable. On success the channel is marked verified.
  # @param channel_id UUID of the webhook channel to test
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'api_v1_team_notifications_channels_channel_id_test_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_team_notifications_channels_get
  # List notification channels
  # Returns every delivery channel configured for the team (email, webhook, and other supported types). Use channel IDs when attaching targets to notification rules.
  # @param [Hash] opts the optional parameters
  # @return [GetNotificationChannelsResponse]
  describe 'api_v1_team_notifications_channels_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_team_notifications_channels_post
  # Create notification channel
  # Creates a delivery channel for the team. Email channels require verification; webhook channels can be verified with the test endpoint.
  # @param create_notification_channel_input Channel name, type, and type-specific configuration
  # @param [Hash] opts the optional parameters
  # @return [GetNotificationChannelResponse]
  describe 'api_v1_team_notifications_channels_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
