=begin
#EmailGuard Public API

#Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

The version of the OpenAPI document: 1.0
Contact: dev@emailguard.co
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Emailguard::InvitesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InvitesApi' do
  before do
    # run before each test
    @api_instance = Emailguard::InvitesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InvitesApi' do
    it 'should create an instance of InvitesApi' do
      expect(@api_instance).to be_instance_of(Emailguard::InvitesApi)
    end
  end

  # unit tests for api_v1_team_members_invites_get
  # List pending team invites
  # Returns invites that have not yet been accepted or expired. Each invite includes the target email, assigned role, and expiry time.
  # @param [Hash] opts the optional parameters
  # @return [ListPublicTeamInvitesResponse]
  describe 'api_v1_team_members_invites_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_team_members_invites_invite_id_delete
  # Cancel a pending invite
  # Revokes a pending invite so it can no longer be accepted. The invite is identified by its UUID from the list invites response.
  # @param invite_id UUID of the pending invite to cancel
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'api_v1_team_members_invites_invite_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_team_members_invites_post
  # Invite a team member
  # Sends an email invite to join the team with the specified role. The invitee must accept before they appear in the members list.
  # @param invite_team_member_input Invitee email and role to assign on acceptance
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'api_v1_team_members_invites_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
