=begin
#EmailGuard Public API

#Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

The version of the OpenAPI document: 1.1
Contact: dev@emailguard.co
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Emailguard::MembersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MembersApi' do
  before do
    # run before each test
    @api_instance = Emailguard::MembersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MembersApi' do
    it 'should create an instance of MembersApi' do
      expect(@api_instance).to be_instance_of(Emailguard::MembersApi)
    end
  end

  # unit tests for api_v1_team_members_get
  # List team members
  # Returns every member of the team, including role, profile fields, and join timestamp. Use the &#x60;user_id&#x60; field when calling member update or remove routes.
  # @param [Hash] opts the optional parameters
  # @return [ListPublicTeamMembersResponse]
  describe 'api_v1_team_members_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_team_members_user_id_delete
  # Remove a team member
  # Removes a user from the team. Identify the member by user account UUID in the path. The team owner cannot be removed through this endpoint.
  # @param user_id User account UUID of the member to remove
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'api_v1_team_members_user_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_team_members_user_id_patch
  # Update a team member role
  # Changes a member&#39;s role or internal notes. Identify the member by user account UUID in the path (not the team membership record ID).
  # @param user_id User account UUID of the member to update
  # @param update_team_member_input New role and/or notes for the member
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'api_v1_team_members_user_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
