=begin
#EmailGuard Public API

#Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

The version of the OpenAPI document: 1.1
Contact: dev@emailguard.co
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Emailguard::RulesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RulesApi' do
  before do
    # run before each test
    @api_instance = Emailguard::RulesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RulesApi' do
    it 'should create an instance of RulesApi' do
      expect(@api_instance).to be_instance_of(Emailguard::RulesApi)
    end
  end

  # unit tests for api_v1_team_notifications_rules_get
  # List notification rules
  # Returns routing rules that map event types to one or more delivery channels. Each rule includes its enabled state and channel targets.
  # @param [Hash] opts the optional parameters
  # @return [GetNotificationRulesResponse]
  describe 'api_v1_team_notifications_rules_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_team_notifications_rules_post
  # Create notification rule
  # Creates a rule that delivers matching events to the specified channels. At least one event type and one channel target are required.
  # @param create_notification_rule_input Rule name, event types, and channel targets
  # @param [Hash] opts the optional parameters
  # @return [IdDataResponse]
  describe 'api_v1_team_notifications_rules_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_team_notifications_rules_rule_id_delete
  # Delete notification rule
  # Permanently deletes a routing rule and its channel assignments.
  # @param rule_id UUID of the notification rule to delete
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'api_v1_team_notifications_rules_rule_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_v1_team_notifications_rules_rule_id_put
  # Update notification rule
  # Updates a rule&#39;s name, description, event types, enabled flag, or channel targets. When &#x60;channels&#x60; is sent it replaces all existing targets.
  # @param rule_id UUID of the notification rule to update
  # @param update_notification_rule_input Fields to update on the rule
  # @param [Hash] opts the optional parameters
  # @return [MessageResponse]
  describe 'api_v1_team_notifications_rules_rule_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
