=begin
#EmailGuard Public API

#Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

The version of the OpenAPI document: 1.2
Contact: dev@emailguard.co
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

# Common files
require 'emailguard_sdk/api_client'
require 'emailguard_sdk/api_error'
require 'emailguard_sdk/api_model_base'
require 'emailguard_sdk/version'
require 'emailguard_sdk/configuration'

# Models
require 'emailguard_sdk/models/base_response'
require 'emailguard_sdk/models/billing_usage_event'
require 'emailguard_sdk/models/billing_usage_item'
require 'emailguard_sdk/models/billing_usage_response'
require 'emailguard_sdk/models/create_notification_channel_input'
require 'emailguard_sdk/models/create_notification_rule_input'
require 'emailguard_sdk/models/email_detect_data'
require 'emailguard_sdk/models/email_detect_evidence'
require 'emailguard_sdk/models/email_detect_response'
require 'emailguard_sdk/models/get_notification_channel_response'
require 'emailguard_sdk/models/get_notification_channels_response'
require 'emailguard_sdk/models/get_notification_events_response'
require 'emailguard_sdk/models/get_notification_rules_response'
require 'emailguard_sdk/models/get_public_team_response'
require 'emailguard_sdk/models/id_data_response'
require 'emailguard_sdk/models/id_data_struct'
require 'emailguard_sdk/models/invite_team_member_input'
require 'emailguard_sdk/models/list_public_team_invites_response'
require 'emailguard_sdk/models/list_public_team_members_response'
require 'emailguard_sdk/models/message_response'
require 'emailguard_sdk/models/notification_channel_response'
require 'emailguard_sdk/models/notification_rule_channel_input'
require 'emailguard_sdk/models/notification_rule_channel_response'
require 'emailguard_sdk/models/notification_rule_response'
require 'emailguard_sdk/models/public_team_invite_response'
require 'emailguard_sdk/models/public_team_member_response'
require 'emailguard_sdk/models/public_team_response'
require 'emailguard_sdk/models/public_update_team_member_input'
require 'emailguard_sdk/models/update_notification_channel_input'
require 'emailguard_sdk/models/update_notification_rule_input'
require 'emailguard_sdk/models/update_team_input'

# APIs
require 'emailguard_sdk/api/billing_api'
require 'emailguard_sdk/api/channels_api'
require 'emailguard_sdk/api/email_api'
require 'emailguard_sdk/api/events_api'
require 'emailguard_sdk/api/invites_api'
require 'emailguard_sdk/api/members_api'
require 'emailguard_sdk/api/rules_api'
require 'emailguard_sdk/api/teams_api'

module Emailguard
  class << self
    # Customize default settings for the SDK using block.
    #   Emailguard.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
require 'emailguard_sdk/facade'
