=begin
#EmailGuard Public API

#Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

The version of the OpenAPI document: 1.0
Contact: dev@emailguard.co
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Emailguard
  class BillingUsageEvent < ApiModelBase
    attr_accessor :delta

    attr_accessor :event_type

    attr_accessor :metadata

    attr_accessor :usage_after

    attr_accessor :usage_before

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'delta' => :'delta',
        :'event_type' => :'event_type',
        :'metadata' => :'metadata',
        :'usage_after' => :'usage_after',
        :'usage_before' => :'usage_before'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'delta' => :'Integer',
        :'event_type' => :'String',
        :'metadata' => :'String',
        :'usage_after' => :'Integer',
        :'usage_before' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Emailguard::BillingUsageEvent` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Emailguard::BillingUsageEvent`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'delta')
        self.delta = attributes[:'delta']
      else
        self.delta = nil
      end

      if attributes.key?(:'event_type')
        self.event_type = attributes[:'event_type']
      else
        self.event_type = nil
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      else
        self.metadata = nil
      end

      if attributes.key?(:'usage_after')
        self.usage_after = attributes[:'usage_after']
      else
        self.usage_after = nil
      end

      if attributes.key?(:'usage_before')
        self.usage_before = attributes[:'usage_before']
      else
        self.usage_before = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @delta.nil?
        invalid_properties.push('invalid value for "delta", delta cannot be nil.')
      end

      if @event_type.nil?
        invalid_properties.push('invalid value for "event_type", event_type cannot be nil.')
      end

      if @metadata.nil?
        invalid_properties.push('invalid value for "metadata", metadata cannot be nil.')
      end

      if @usage_after.nil?
        invalid_properties.push('invalid value for "usage_after", usage_after cannot be nil.')
      end

      if @usage_before.nil?
        invalid_properties.push('invalid value for "usage_before", usage_before cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @delta.nil?
      return false if @event_type.nil?
      return false if @metadata.nil?
      return false if @usage_after.nil?
      return false if @usage_before.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] delta Value to be assigned
    def delta=(delta)
      if delta.nil?
        fail ArgumentError, 'delta cannot be nil'
      end

      @delta = delta
    end

    # Custom attribute writer method with validation
    # @param [Object] event_type Value to be assigned
    def event_type=(event_type)
      if event_type.nil?
        fail ArgumentError, 'event_type cannot be nil'
      end

      @event_type = event_type
    end

    # Custom attribute writer method with validation
    # @param [Object] metadata Value to be assigned
    def metadata=(metadata)
      if metadata.nil?
        fail ArgumentError, 'metadata cannot be nil'
      end

      @metadata = metadata
    end

    # Custom attribute writer method with validation
    # @param [Object] usage_after Value to be assigned
    def usage_after=(usage_after)
      if usage_after.nil?
        fail ArgumentError, 'usage_after cannot be nil'
      end

      @usage_after = usage_after
    end

    # Custom attribute writer method with validation
    # @param [Object] usage_before Value to be assigned
    def usage_before=(usage_before)
      if usage_before.nil?
        fail ArgumentError, 'usage_before cannot be nil'
      end

      @usage_before = usage_before
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          delta == o.delta &&
          event_type == o.event_type &&
          metadata == o.metadata &&
          usage_after == o.usage_after &&
          usage_before == o.usage_before
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [delta, event_type, metadata, usage_after, usage_before].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
