=begin
#EmailGuard Public API

#Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

The version of the OpenAPI document: 1.0
Contact: dev@emailguard.co
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Emailguard
  class CreateNotificationRuleInput < ApiModelBase
    # One or more channel targets to notify when matching events occur.
    attr_accessor :channels

    # Optional rule conditions (e.g. usage_threshold for USAGE_API_THRESHOLD).
    attr_accessor :conditions

    # Optional longer description of what the rule does.
    attr_accessor :description

    # Event type identifiers this rule listens for (at least one required).
    attr_accessor :event_types

    # When false, the rule is stored but does not deliver events.
    attr_accessor :is_enabled

    # Display name for the rule.
    attr_accessor :name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'channels' => :'channels',
        :'conditions' => :'conditions',
        :'description' => :'description',
        :'event_types' => :'event_types',
        :'is_enabled' => :'is_enabled',
        :'name' => :'name'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'channels' => :'Array<NotificationRuleChannelInput>',
        :'conditions' => :'Hash<String, Object>',
        :'description' => :'String',
        :'event_types' => :'Array<String>',
        :'is_enabled' => :'Boolean',
        :'name' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Emailguard::CreateNotificationRuleInput` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Emailguard::CreateNotificationRuleInput`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'channels')
        if (value = attributes[:'channels']).is_a?(Array)
          self.channels = value
        end
      else
        self.channels = nil
      end

      if attributes.key?(:'conditions')
        if (value = attributes[:'conditions']).is_a?(Hash)
          self.conditions = value
        end
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'event_types')
        if (value = attributes[:'event_types']).is_a?(Array)
          self.event_types = value
        end
      else
        self.event_types = nil
      end

      if attributes.key?(:'is_enabled')
        self.is_enabled = attributes[:'is_enabled']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @channels.nil?
        invalid_properties.push('invalid value for "channels", channels cannot be nil.')
      end

      if @event_types.nil?
        invalid_properties.push('invalid value for "event_types", event_types cannot be nil.')
      end

      if @event_types.length < 1
        invalid_properties.push('invalid value for "event_types", number of items must be greater than or equal to 1.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @channels.nil?
      return false if @event_types.nil?
      return false if @event_types.length < 1
      return false if @name.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] channels Value to be assigned
    def channels=(channels)
      if channels.nil?
        fail ArgumentError, 'channels cannot be nil'
      end

      @channels = channels
    end

    # Custom attribute writer method with validation
    # @param [Object] event_types Value to be assigned
    def event_types=(event_types)
      if event_types.nil?
        fail ArgumentError, 'event_types cannot be nil'
      end

      if event_types.length < 1
        fail ArgumentError, 'invalid value for "event_types", number of items must be greater than or equal to 1.'
      end

      @event_types = event_types
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          channels == o.channels &&
          conditions == o.conditions &&
          description == o.description &&
          event_types == o.event_types &&
          is_enabled == o.is_enabled &&
          name == o.name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [channels, conditions, description, event_types, is_enabled, name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
